### PR TITLE
flipped min heap sort

### PR DESCRIPTION
**Pull request by landfillbaby**
like min heap sort but doesn't need the flip at the end due to doing everything in reverse
might have off by 1 errors, needs testing, could also be rewritten for optimization probably
i would have tested it myself but my hard drive died a few says ago :(

### CODE REVIEW

**Comment by landfillbaby** [comment]
alright, i tested it and it should work fine :)

**Comment by ColinRafaelPerez08** [comment]
I attempted to add it, and when i went to go compile it, there's errors saying "error: cannot find symbol" and it's mostly just from punctuation marks.
image 
image

**Comment by landfillbaby** [comment]
oops! forgot to import templates.Sort! should be fixed now

**Comment by ColinRafaelPerez08** [comment]
This is the only error that appeared now. Is it any progress?
image

**Comment by landfillbaby** [comment]
ok does this work now?? i really have no idea

**Comment by landfillbaby** [comment]
hey i've just thought. would it be better to just replace the existing MinHeapSort with this? i could modify templates.HeapSorting instead of adding a new file?

**Pull request merged**
