### PR TITLE
A newer, better Array Visualizer

### PR DESCRIPTION
**Pull request by fundamentals-fontdevelopment**
— Over four thousand new array lengths to choose from
— 121 outstanding sorting algorithms
— New default sound is the WAV mode, only emitting sound on comparisons and shuffles
— 25 shuffles for comprehensive testing
— Skip Sort properly restores the speed
— Check for sorting properly produces an error when necessary

### CODE REVIEW

**Comment by MusicTheorist** [comment]
This fork of ArrayV was created with an older version. It will take a while to check through your work and merge changes.

**Comment by fundamentals-fontdevelopment** [comment]
YOU are invalid.

**Comment by MusicTheorist** [comment]
@fundamentals-fontdevelopment I appreciate the compliment. :)

**Comment by EilrahcF** [comment]
> 
> 
> @fundamentals-fontdevelopment I appreciate the compliment. :)

Oof, what a savage

**Pull request closed without merging**
